export default {
  DEFAULT_RANDOMNESS: 10,
  DEFAULT_LEARNING_RATE: 20,
  DEFAULT_DISCOUNT_FACTOR: 90,
  DEFAULT_EXPLORATION_RATE: 10,
  TRIAL_INTERVAL: 50,
  MAX_NUMBER_OF_STEPS: 100,
  MAX_NUMBER_OF_TRIALS: 500,
  FINISH_REWARD: 100,
  PATH_REWARD: -1,
  PIT_REWARD: -100,
  CONVERGANCE_TEST: 70
};
